### PR TITLE
Fix typo in box merge

### PR DESCRIPTION
**Pull request by wheezy1749**
Fixed box merge logic to correctly merge the boxes into a larger box. Looks like a typo. Was causing mosaics to flash for a frame or causing some mosaics to not be cleaned when boxes were nearby one another.

### CODE REVIEW

**Comment by wheezy1749** [comment]
There is still another issue I'm seeing sometimes when the merged boxes/masks go from being combined to being split. One of them doesn't get cleaned for a single frame sometimes. Still trying to find the source of that though.

**Comment by wheezy1749** [comment]
Added a try/except to the main cli portion. There seems to be an 'off by 1' issue with frame numbers in the code that is completely killing the progress at the end of a video. Maybe we should catch everything here. No reason to lose the progress of an entire run because of something. Should always attempt to produce a result.

**Comment by ladaapp** [comment]
Regarding the frame count issue:

We get the frame count in `video_utils::get_video_meta_data` via ffprobe ``. It tries to read it from the files metadata but if its not available then we get it via opencv which itself estimates it by `frame_duration * fps` which could indeed be not totally correct. For the files I tested it with this was fine but if you've hit files where this is an issue it would be great to have something more robust.

I see two options, either we 1) count the frames (in ffprobe this could be done with the `-count_frames` argument) or we 2) catch the error and handle it gracefully.

1) Would be easiest to implement: replace the opencv (time-based calculation of of frame count) fallback with the ffprobe using the count_frames arg. This will get us an accurate frame count but will be super slow for long videos as it will need to decode the whole video in order to count all frames one-by-one

2) catch the exception where we call `next(video_utils::VideoReader.frames())`. if this happened the frame count we got earlier was incorrect and we already processed all frames of the input video. Now we need to properly clean up (same logic as we would have hit the last frame according to our frame count) -> e.g. complete the currently running scene.

Let's go with 2) as 1) would just be too slow for files longer than a few minutes.

**Comment by wheezy1749** [comment]
> Let's go with 2) as 1) would just be too slow for files longer than a few minutes.

Agreed. It's easier to just catch the case when we are off by one. Where I added is probably not the place you want to do it though. Feel free to fix that outside this PR because I'm still getting familiar with the code. 

Biggest issue is the min/max typo though. If you want to cherry-pick that from here or add it yourself. Fix greatly reduces "flashing" when boxes are merging/splitting. Though, like I said, there is still "flashing" mosaics showing sometimes for another reason I'm trying to pinpoint. It's happening on box merge frame still but I don't know why.

**Comment by ladaapp** [comment]
@wheezy1749 There is a non-zero chance I fixed it in https://github.com/ladaapp/lada/commit/76a8fe51ee17efe2d6baf696a7f459662c01a9ce
Can you give it a try if it works for your files?

If can revert your changes in this PR except the fix for the min/box box thingy I'd be happy to merge it.

**Comment by wheezy1749** [comment]
> @wheezy1749 There is a non-zero chance I fixed it in [76a8fe5](https://github.com/ladaapp/lada/commit/76a8fe51ee17efe2d6baf696a7f459662c01a9ce) Can you give it a try if it works for your files?

Sure. I'll test it soon.

> If can revert your changes in this PR except the fix for the min/box box thingy I'd be happy to merge it.

Reverted to just the min/max fix.

**Comment by ladaapp** [comment]
Done, thanks for the fix!

**Pull request merged**
